// Code generated by MockGen. DO NOT EDIT.
// Source: oauth2.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_provider.go -package=mocks -source=oauth2.go RedirectFlowProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	upstream "github.com/stacklok/toolhive/pkg/authserver/upstream"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityProvider is a mock of IdentityProvider interface.
type MockIdentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderMockRecorder
	isgomock struct{}
}

// MockIdentityProviderMockRecorder is the mock recorder for MockIdentityProvider.
type MockIdentityProviderMockRecorder struct {
	mock *MockIdentityProvider
}

// NewMockIdentityProvider creates a new mock instance.
func NewMockIdentityProvider(ctrl *gomock.Controller) *MockIdentityProvider {
	mock := &MockIdentityProvider{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityProvider) EXPECT() *MockIdentityProviderMockRecorder {
	return m.recorder
}

// Type mocks base method.
func (m *MockIdentityProvider) Type() upstream.ProviderType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(upstream.ProviderType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockIdentityProviderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockIdentityProvider)(nil).Type))
}

// MockRedirectFlowProvider is a mock of RedirectFlowProvider interface.
type MockRedirectFlowProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectFlowProviderMockRecorder
	isgomock struct{}
}

// MockRedirectFlowProviderMockRecorder is the mock recorder for MockRedirectFlowProvider.
type MockRedirectFlowProviderMockRecorder struct {
	mock *MockRedirectFlowProvider
}

// NewMockRedirectFlowProvider creates a new mock instance.
func NewMockRedirectFlowProvider(ctrl *gomock.Controller) *MockRedirectFlowProvider {
	mock := &MockRedirectFlowProvider{ctrl: ctrl}
	mock.recorder = &MockRedirectFlowProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectFlowProvider) EXPECT() *MockRedirectFlowProviderMockRecorder {
	return m.recorder
}

// AuthorizationURL mocks base method.
func (m *MockRedirectFlowProvider) AuthorizationURL(state, codeChallenge string, opts ...upstream.AuthorizationOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{state, codeChallenge}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AuthorizationURL", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizationURL indicates an expected call of AuthorizationURL.
func (mr *MockRedirectFlowProviderMockRecorder) AuthorizationURL(state, codeChallenge any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{state, codeChallenge}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizationURL", reflect.TypeOf((*MockRedirectFlowProvider)(nil).AuthorizationURL), varargs...)
}

// ExchangeCodeForIdentity mocks base method.
func (m *MockRedirectFlowProvider) ExchangeCodeForIdentity(ctx context.Context, code, codeVerifier, nonce string) (*upstream.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCodeForIdentity", ctx, code, codeVerifier, nonce)
	ret0, _ := ret[0].(*upstream.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCodeForIdentity indicates an expected call of ExchangeCodeForIdentity.
func (mr *MockRedirectFlowProviderMockRecorder) ExchangeCodeForIdentity(ctx, code, codeVerifier, nonce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCodeForIdentity", reflect.TypeOf((*MockRedirectFlowProvider)(nil).ExchangeCodeForIdentity), ctx, code, codeVerifier, nonce)
}

// RefreshTokens mocks base method.
func (m *MockRedirectFlowProvider) RefreshTokens(ctx context.Context, refreshToken, expectedSubject string) (*upstream.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", ctx, refreshToken, expectedSubject)
	ret0, _ := ret[0].(*upstream.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockRedirectFlowProviderMockRecorder) RefreshTokens(ctx, refreshToken, expectedSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockRedirectFlowProvider)(nil).RefreshTokens), ctx, refreshToken, expectedSubject)
}

// Type mocks base method.
func (m *MockRedirectFlowProvider) Type() upstream.ProviderType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(upstream.ProviderType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRedirectFlowProviderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRedirectFlowProvider)(nil).Type))
}

// MockDirectAssertionProvider is a mock of DirectAssertionProvider interface.
type MockDirectAssertionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDirectAssertionProviderMockRecorder
	isgomock struct{}
}

// MockDirectAssertionProviderMockRecorder is the mock recorder for MockDirectAssertionProvider.
type MockDirectAssertionProviderMockRecorder struct {
	mock *MockDirectAssertionProvider
}

// NewMockDirectAssertionProvider creates a new mock instance.
func NewMockDirectAssertionProvider(ctrl *gomock.Controller) *MockDirectAssertionProvider {
	mock := &MockDirectAssertionProvider{ctrl: ctrl}
	mock.recorder = &MockDirectAssertionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectAssertionProvider) EXPECT() *MockDirectAssertionProviderMockRecorder {
	return m.recorder
}

// ResolveIdentity mocks base method.
func (m *MockDirectAssertionProvider) ResolveIdentity(ctx context.Context) (*upstream.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIdentity", ctx)
	ret0, _ := ret[0].(*upstream.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIdentity indicates an expected call of ResolveIdentity.
func (mr *MockDirectAssertionProviderMockRecorder) ResolveIdentity(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIdentity", reflect.TypeOf((*MockDirectAssertionProvider)(nil).ResolveIdentity), ctx)
}

// Type mocks base method.
func (m *MockDirectAssertionProvider) Type() upstream.ProviderType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(upstream.ProviderType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockDirectAssertionProviderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockDirectAssertionProvider)(nil).Type))
}
