apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spiffe-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "SPIFFE Root CA"
  duration: 87600h
  secretName: spiffe-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
